name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Kivy APK for Android
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            build-essential \
            libffi-dev \
            libssl-dev \
            python3-dev \
            libsqlite3-dev \
            libgmp-dev \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libx11-dev \
            libxft-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libbz2-dev \
            git

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade Cython buildozer

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
